language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install --upgrade numpy cython
  - pip install --upgrade pytest pytest-cov pytest-pep8 codecov
  - pip install -e .

script:
  - pytest --cov mdbenchmark -v --pep8 mdbenchmark

after_success:
  - codecov
