language: generic
sudo: false

branches:
  only:
    - master

env:
  global:
    - PYTHON_VERSION=3.6
    - MAIN_CMD="pytest"
    - SETUP_CMD="--cov mdbenchmark --pep8 mdbenchmark -v"
    - CONDA_DEPENDENCIES="cython mdsynthesis jinja2 click pandas matplotlib pytest-pep8 codecov xdg<2"
    - CONDA_CHANNELS="conda-forge"
    - NUMPY_VERSION=stable
  matrix:
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=2.7

matrix:
  fast_finish: true
  include:
    - os: osx
      env: PYTHON_VERSION=2.7

    - os: linux
      env: PIP_DEPENDENCIES="restructuredtext_lint"
           MAIN_CMD="rst-lint README.rst"
           SETUP_CMD=""

install:
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - pip install -e .

script:
  - $MAIN_CMD $SETUP_CMD

after_success:
  - codecov
