language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

install:
  - pip install --upgrade numpy cython
  - pip install -e .
  - pip install pytest pytest-cov pytest-pep8

script:
  - pytest --cov mdbenchmark -v --pep8 mdbenchmark
