[build-system]
requires = ["setuptools", "wheel"]
build-backend = 'setuptools.build_meta'

[tool.towncrier]
package = "mdbenchmark"
filename = "CHANGELOG.rst"
directory = "changelog/"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/bio-phys/MDBenchmark/issues/{issue}>`_"
